apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-merch
  namespace: monitoring
  labels:
    app: alert-merch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-merch
  template:
    metadata:
      labels:
        app: alert-merch
    spec:
      containers:
      - name: alert-merch
        image: registry.jlpay.com/middleware/alert-merch:v1.4 # ← 替换为你构建推送到镜像仓库的镜像名
        imagePullPolicy: Always
        env:
        - name: ORACLE_DSN
          valueFrom:
            secretKeyRef:
              name: oracle-secret
              key: dsn
        - name: WECOM_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: wecom-secret
              key: webhook
        - name: WECOM_WEBHOOK2
          valueFrom:
            secretKeyRef:
              name: wecom-secret
              key: webhook2
        - name: WECOM_WEBHOOK3
          valueFrom:
            secretKeyRef:
              name: wecom-secret
              key: webhook3
        - name: PERSIST_PATH
          value: "/app/data"
        - name: TASK_TIMEOUT_MINUTES
          value: "3"
        - name: CHECK_INTERVAL_SECONDS
          value: "10"
        - name: UNFINISHED_TIMEOUT_MINUTES
          value: "10"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
      nodeSelector:
        oteltype: loadbalancer
      volumes:
      - hostPath:
          path: /data/alert-merch
          type: DirectoryOrCreate
        name: data-volume

