apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-merch-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # 使用默认的存储类 