apiVersion: v1
kind: Service
metadata:
  name: alert-merch
  namespace: alert-merch
  labels:
    app: alert-merch
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: alert-merch 